baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Envirocate'
theme = 'quint'

# Theme config. Your config (yoursite/hugo.toml) overrides this one.

paginate = 4                        # Number of posts to show on a list page
summaryLength = 20                  # Number of characters in your card summaries


[params]
# css = ["css/custom.css"]            # Your custom CSS overrides, stored in yoursite/static/
numImages = 10                      # Number of random images to choose from for banners (in themes/quint/static/images)
phrase = 'Revealing | Advocating | Changing'
# sub = 'Dedicated to providing current information on environmental issues'
copyright = 'A Student-led Project'
# Customize your social links below!

# [[params.social]]
#     url = "mailto:me"
#     icon = "/social/email.png"
#     name = "Email"

# [[params.social]]
#     url = "https://instagram.com"
#     icon = "/social/instagram.svg"
#     name = "Instagram"
